{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "a65744c9",
   "metadata": {
    "vscode": {
     "languageId": "markdown"
    }
   },
   "outputs": [],
   "source": [
    "# Libraries\n",
    "\n",
    "import os\n",
    "import re\n",
    "import json\n",
    "import time\n",
    "import requests\n",
    "from typing import List, Dict, Any\n",
    "from bs4 import BeautifulSoup\n",
    "from fastapi import FastAPI, HTTPException\n",
    "from pydantic import BaseModel\n",
    "from langchain_core.documents import Document\n",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
    "from langchain_openai import OpenAIEmbeddings\n",
    "from langchain_community.vectorstores import FAISS\n",
    "from langchain_openai import ChatOpenAI\n",
    "from langchain_classic.chains import RetrievalQA\n",
    "from langchain_core.prompts import PromptTemplate\n",
    "from langchain_community.tools import DuckDuckGoSearchResults\n",
    "from duckduckgo_search import DDGS\n",
    "from youtube_transcript_api import YouTubeTranscriptApi"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8ef1cf26",
   "metadata": {
    "vscode": {
     "languageId": "markdown"
    }
   },
   "outputs": [],
   "source": [
    "# Configuration - Keys placeholders\n",
    "OPENAI_API_KEY = ${{DS-Env.OPENAI_API_KEY}}\n",
    "YOUTUBE_API_KEY = ${{DS-Env.YOUTUBE_API_KEY}}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "79572ceb",
   "metadata": {
    "vscode": {
     "languageId": "markdown"
    }
   },
   "outputs": [],
   "source": [
    "INDEX_PATH = \"chef_faiss_index\"\n",
    "\n",
    "# apply keys to env so LangChain/OpenAI clients pick them up\n",
    "os.environ[\"OPENAI_API_KEY\"] = OPENAI_API_KEY\n",
    "\n",
    "# Utilities\n",
    "def clean_text(text: str) -> str:\n",
    "    text = re.sub(r\"\\s+\", \" \", text).strip()\n",
    "    return text\n",
    "\n",
    "# Ingestion pipelines\n",
    "def youtube_search_video_ids(query: str, max_results: int = 5) -> List[str]:\n",
    "    url = \"https://www.googleapis.com/youtube/v3/search\"\n",
    "    params = {\n",
    "        \"part\": \"id\",\n",
    "        \"q\": query,\n",
    "        \"type\": \"video\",\n",
    "        \"maxResults\": max_results,\n",
    "        \"key\": YOUTUBE_API_KEY,\n",
    "    }\n",
    "    r = requests.get(url, params=params)\n",
    "    r.raise_for_status()\n",
    "    items = r.json().get(\"items\", [])\n",
    "    return [it[\"id\"][\"videoId\"] for it in items if it.get(\"id\", {}).get(\"videoId\")]\n",
    "\n",
    "def fetch_youtube_transcript(video_id: str) -> str:\n",
    "    try:\n",
    "        parts = YouTubeTranscriptApi.get_transcript(video_id)\n",
    "        text = \" \".join([p[\"text\"] for p in parts])\n",
    "        return clean_text(text)\n",
    "    except Exception:\n",
    "        return \"\"\n",
    "\n",
    "def duckduckgo_search(query: str, num: int = 10) -> List[Dict[str, Any]]:\n",
    "    # No API key required\n",
    "    results = []\n",
    "    with DDGS() as ddg:\n",
    "        for r in ddg.text(query, max_results=num):\n",
    "            results.append({\n",
    "                \"title\": r.get(\"title\"),\n",
    "                \"link\": r.get(\"href\"),\n",
    "                \"snippet\": r.get(\"body\")\n",
    "            })\n",
    "    return results\n",
    "\n",
    "def fetch_page_text(url: str) -> str:\n",
    "    try:\n",
    "        r = requests.get(url, timeout=10, headers={\"User-Agent\": \"RAG-Chef/1.0\"})\n",
    "        r.raise_for_status()\n",
    "        soup = BeautifulSoup(r.text, \"html.parser\")\n",
    "        # remove scripts/styles\n",
    "        for t in soup([\"script\", \"style\", \"noscript\", \"header\", \"footer\", \"nav\", \"aside\"]):\n",
    "            t.extract()\n",
    "        texts = [p.get_text(separator=\" \", strip=True) for p in soup.find_all([\"p\", \"li\", \"h1\", \"h2\", \"h3\"])]\n",
    "        return clean_text(\" \".join([t for t in texts if t]))\n",
    "    except Exception:\n",
    "        return \"\"\n",
    "\n",
    "# Indexing\n",
    "class RAGChefAgent:\n",
    "    def __init__(self, index_path: str = INDEX_PATH):\n",
    "        self.index_path = index_path\n",
    "        self.splitter = RecursiveCharacterTextSplitter(chunk_size=800, chunk_overlap=100)\n",
    "        self.embeddings = OpenAIEmbeddings()\n",
    "        self.index = None  # FAISS instance\n",
    "        self.llm = ChatOpenAI(temperature=0.2, model=\"gpt-4o-mini\")  # change model if needed\n",
    "        self.qa_chain = None\n",
    "\n",
    "    def _docs_to_index(self, docs: List[Document]) -> None:\n",
    "        if not docs:\n",
    "            return\n",
    "        if self.index:\n",
    "            self.index.add_documents(docs)\n",
    "        else:\n",
    "            self.index = FAISS.from_documents(docs, self.embeddings)\n",
    "        # persist\n",
    "        self.index.save_local(self.index_path)\n",
    "\n",
    "    def ingest_youtube(self, query: str, max_results: int = 5):\n",
    "        ids = youtube_search_video_ids(query, max_results=max_results)\n",
    "        docs = []\n",
    "        for vid in ids:\n",
    "            txt = fetch_youtube_transcript(vid)\n",
    "            if not txt:\n",
    "                continue\n",
    "            for chunk in self.splitter.split_text(txt):\n",
    "                docs.append(Document(page_content=chunk, metadata={\"source\": f\"youtube:{vid}\", \"query\": query}))\n",
    "        self._docs_to_index(docs)\n",
    "\n",
    "    def ingest_google(self, query: str, max_results: int = 10):\n",
    "        results = duckduckgo_search(query, num=max_results)\n",
    "        docs = []\n",
    "        for res in results:\n",
    "            link = res.get(\"link\") or res.get(\"url\")\n",
    "            text = fetch_page_text(link) if link else \"\"\n",
    "            if not text:\n",
    "                continue\n",
    "            for chunk in self.splitter.split_text(text):\n",
    "                docs.append(Document(page_content=chunk, metadata={\"source\": link, \"title\": res.get(\"title\")}))\n",
    "        self._docs_to_index(docs)\n",
    "\n",
    "    def ingest_blogs(self, urls: List[str]):\n",
    "        docs = []\n",
    "        for url in urls:\n",
    "            text = fetch_page_text(url)\n",
    "            if not text:\n",
    "                continue\n",
    "            for chunk in self.splitter.split_text(text):\n",
    "                docs.append(Document(page_content=chunk, metadata={\"source\": url}))\n",
    "        self._docs_to_index(docs)\n",
    "\n",
    "    def load_index(self):\n",
    "        if os.path.exists(self.index_path):\n",
    "            self.index = FAISS.load_local(self.index_path, self.embeddings)\n",
    "        else:\n",
    "            self.index = None\n",
    "        if self.index:\n",
    "            retriever = self.index.as_retriever(search_kwargs={\"k\": 5})\n",
    "            prompt = PromptTemplate(\n",
    "                input_variables=[\"context\", \"question\"],\n",
    "                template=(\n",
    "                    \"You are a helpful cooking chef assistant. Use the provided context (web, videos, blogs) to answer \"\n",
    "                    \"the user's question in a friendly, actionable way. Provide steps, timings, and ingredient notes when relevant.\\n\\n\"\n",
    "                    \"Context:\\n{context}\\n\\nQuestion: {question}\\nAnswer:\"\n",
    "                ),\n",
    "            )\n",
    "            self.qa_chain = RetrievalQA.from_chain_type(\n",
    "                llm=self.llm, chain_type=\"stuff\", retriever=retriever, return_source_documents=True, chain_type_kwargs={\"prompt\": prompt}\n",
    "            )\n",
    "\n",
    "    def ask(self, question: str) -> Dict[str, Any]:\n",
    "        if not self.index:\n",
    "            raise RuntimeError(\"Index not loaded. Call load_index() or ingest data first.\")\n",
    "        res = self.qa_chain({\"query\": question})\n",
    "        answer = res.get(\"result\")\n",
    "        docs = res.get(\"source_documents\", [])\n",
    "        sources = [{\"source\": d.metadata.get(\"source\"), \"excerpt\": d.page_content[:300]} for d in docs]\n",
    "        return {\"answer\": answer, \"sources\": sources}\n",
    "\n",
    "# FastAPI deployment\n",
    "app = FastAPI()\n",
    "agent = RAGChefAgent()\n",
    "# try to load existing index on startup\n",
    "try:\n",
    "    agent.load_index()\n",
    "except Exception:\n",
    "    pass\n",
    "\n",
    "class IngestRequest(BaseModel):\n",
    "    mode: str  # \"youtube\" | \"google\" | \"blogs\"\n",
    "    query: str = None\n",
    "    urls: List[str] = None\n",
    "    max_results: int = 5\n",
    "\n",
    "class AskRequest(BaseModel):\n",
    "    question: str\n",
    "\n",
    "@app.post(\"/ingest\")\n",
    "def ingest(req: IngestRequest):\n",
    "    try:\n",
    "        if req.mode == \"youtube\":\n",
    "            if not req.query:\n",
    "                raise HTTPException(status_code=400, detail=\"query required for youtube\")\n",
    "            agent.ingest_youtube(req.query, max_results=req.max_results or 5)\n",
    "        elif req.mode == \"google\":\n",
    "            if not req.query:\n",
    "                raise HTTPException(status_code=400, detail=\"query required for google\")\n",
    "            agent.ingest_google(req.query, max_results=req.max_results or 10)\n",
    "        elif req.mode == \"blogs\":\n",
    "            if not req.urls:\n",
    "                raise HTTPException(status_code=400, detail=\"urls required for blogs\")\n",
    "            agent.ingest_blogs(req.urls)\n",
    "        else:\n",
    "            raise HTTPException(status_code=400, detail=\"invalid mode\")\n",
    "        agent.load_index()\n",
    "        return {\"status\": \"ok\"}\n",
    "    except Exception as e:\n",
    "        raise HTTPException(status_code=500, detail=str(e))\n",
    "\n",
    "@app.post(\"/ask\")\n",
    "def ask(req: AskRequest):\n",
    "    try:\n",
    "        out = agent.ask(req.question)\n",
    "        return out\n",
    "    except Exception as e:\n",
    "        raise HTTPException(status_code=500, detail=str(e))\n",
    "\n",
    "@app.get(\"/status\")\n",
    "def status():\n",
    "    return {\"index_loaded\": agent.index is not None}\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
